#!/bin/bash

og_user=$(who am i | awk '{print $1}')
while getopts "pc" opt; do
  case "${opt}" in 
    p)
      if [[ $(id -u ) -ne 0 ]]; then
        echo "Run as Sudo User"
        exit 1
      fi
      echo "These are the packages that are to be downloaded: 
$(cat /home/$og_user/project1/packages.txt)

[Y/N] to proceed:"
      read input
      if [[ $input == "y" || $input == "Y" ]]; then
        ./install $og_user
      else
        echo "
Open the packages.txt file and add any other packages that you wish to download"
        exit 1
      fi
      ;;
    c) 
      ./config_files $og_user
      ;;
    "?")
      echo "Use the option -p for installing the packages or -c for installing the configuration files with symbolic links"
      exit 1
      ;;
  esac
done 

if [[ $OPTIND -eq 1 ]]; then
  echo  "Use the option -p for installing the packages or -c for installing the configuration files with symbolic links"
  exit 1
fit 1
fi
